merge actualizacion de validaciones para endpoints
Nervios-de-Acero/Avocado-Android pull request #42
Opened 2024-06-02 18:38 UTC by RochettiUriel

Se agregan validaciones faltantes sacadas del otro repositorio. Incluida la funcion validacionJSON

2024-06-02 18:59 UTC, Loreaylen requested changes
Está perfecto Uri, solamente faltaría que importes los módulos al principio de los archivos y quedaría.

2024-06-02 18:59 UTC, Loreaylen commented on Backend/routes/receta.js
> +router.post('/agregarReceta', checkSchema(validaciones), funcionescomunes.validarJSON, (req, res)=>{
Faltaría importar "funciones comunes" en el módulo

2024-06-02 18:59 UTC, Loreaylen commented on Backend/routes/usuario.js
> +router.put('/actualizarPerfil', checkSchema(validaciones), funcionescomunes.validarJSON, (req, res) => {
Importar "funcionescomunes"

2024-06-02 18:59 UTC, Loreaylen commented on Backend/routes/registro.js
> +router.post('/', checkSchema(validaciones), funcionescomunes.validarJSON, (req, res) => {
Importar "funcionescomunes"

2024-06-03 20:23 UTC, RochettiUriel commented on Backend/routes/receta.js
> +router.post('/agregarReceta', checkSchema(validaciones), funcionescomunes.validarJSON, (req, res)=>{
listo

2024-06-03 20:23 UTC, RochettiUriel commented on Backend/routes/registro.js
> +router.post('/', checkSchema(validaciones), funcionescomunes.validarJSON, (req, res) => {
listo

2024-06-03 20:23 UTC, RochettiUriel commented on Backend/routes/usuario.js
> +router.put('/actualizarPerfil', checkSchema(validaciones), funcionescomunes.validarJSON, (req, res) => {
listo

2024-06-03 21:59 UTC, Loreaylen approved these changes
Excelente Uri

2024-06-03 22:15 UTC, merged